### ISSUE TITLE
Getting a Proxy Error

### ISSUE THREAD

**Issue by wpk12345** [StephenGrider/FullstackReactCode#24]

**Comment by jkp9qd** [comment]
I have the same Proxy error as well:

Proxy error: Could not proxy request /api/current_user from localhost:3000 to http://localhost:5000.
[1] See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).
[1] 
[1] [HPM] Error occurred while trying to proxy request /api/current_user from localhost:3000 to http://localhost:5000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

Did you fix the error?

**Comment by wpk12345** [comment]
Yes but a month or so ago. I’ll have to look at the solution he sent and try to get back. Message him. He’s good about getting back.

**Comment by jkp9qd** [comment]
Ok, thank you.

Best,

Jarvis

**Comment by jkp9qd** [comment]
Hello Stephen,

Can you point me in the right direction to get fix this error?

Proxy error: Could not proxy request /api/current_user from localhost:3000
to http://localhost:5000.

[1] See https://nodejs.org/api/errors.html#errors_common_system_errors for
more information (ECONNREFUSED).

[1]

[1] [HPM] Error occurred while trying to proxy request /api/current_user
from localhost:3000 to http://localhost:5000 (ECONNREFUSED) (
https://nodejs.org/api/errors.html#errors_common_system_errors)

Best,

Jarvis

**Comment by eponymz** [comment]
If you run lsof -i :5000 then grab the id from the output then run kill <id> then npm run dev you should be good.

**Comment by eponymz** [comment]
The command needs to be syntactically identical to what I put. <lsof -i
:5000> make sure there is a space before typing the port.

**Comment by maevadevs** [comment]
I get this error as well, sporadically... Not sure yet what the fix is but here is what I found.

I broke down the way to run the dev server (instead of using concurrently) and it seems the error is coming from the frontend. I get no error when saving a backend file, only from the client directory. Here is the error message in the front-end console:

```
Proxy error: Could not proxy request /api/current_user from localhost:3000 to http://localhost:5000.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

[HPM] Error occurred while trying to proxy request /api/current_user from localhost:3000 to http://localhost:5000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```
An error is also displayed in Chrome: Internal Server Error 500
After debugging the one in Chrome, it appears the error is coming from `this.props.fetchUser()` under `componentDidMount` of `App.js`

Only when saving a file in the `client` folder and **both** create-react-app's auto-reload and nodemon's auto-reload kick in. I believe this is creating a race-condition for the proxy at the frontend as the bother server are temporarily down. If nodemon restart first then proxy works. If not, `componentDidMount` and `fetchUser` in `App` dispatch the action too earlier...

**Comment by Johnny00520** [comment]
I have this issue when I try the bcrypt to hash the request password. So you think this is race-condition issue? If I don't use the hash function, I got 'Proxy error: Could not proxy request /api/signup from localhost:3000 to http://localhost:5005.
[1] See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).'

I even try to ignore the /client in packet.json, but I still have the same error. What do you think?

**Comment by polyrhythmm** [comment]
Did anyone solve this?

**Comment by Lilzer2018** [comment]
Hi 
I have the same issue
rror occurred while trying to proxy request /search/AH from localhost:3000 to http://localhost:5000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

please help !

**Comment by alireza1989** [comment]
I had the same issue.  The problem is that you probably forgot to include dev.js in the config folder when you cloned the project.  Since we did not want to include our Google client ID and secrets in the github repo we added that file to .gitignore.  

I don't know why the error is not self explanatory but it will be solved once you add google creds (dev.js) files to the project.  

Cheers

**Comment by emmjaykay** [comment]
I had this same issue but for different reasons -- I had my ports switched on the backend and frontend code.

In my setup, the react app should run on port 3001. In the package.json, the proxy is set up to forward things to port 3000. Port 3000 is where the backend node app runs.

You can do `export PORT=3001` when starting the react app and it cleared it up in my install.

**Comment by Samyaryal** [comment]
What is the solution of this problem??

**Comment by eponymz** [comment]
@Samyaryal [this](https://github.com/StephenGrider/FullstackReactCode/issues/24#issuecomment-397097815) the error is stating that the connection to Port 5000 was refused. So make sure you don't have anything running on it.

**Comment by netEmmanuel** [comment]
Did anyone get to resolve this issue?

**Comment by brentEvans** [comment]
None of the solutions posted here worked for me.  Seems to be an identical error message:

[HPM] Error occurred while trying to proxy request /api/current_user from localhost:3000 to http://localhost:5000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

Anyone figure this out?

**Comment by onomemineadamu** [comment]
Replace localhost to 127.0.0.1 in your package.json proxy

**Comment by nelsonomuto** [comment]
Using a parser like cookie parser or body parser can cause this issue

**Comment by kawsher-hamid98** [comment]
"server": "nodemon server.js --ignore './client/'"
try this..

**Comment by polyrhythmm** [comment]
> "server": "nodemon server.js --ignore './client/'"
> try this..

THAT WORKED!

**Comment by polyrhythmm** [comment]
> "server": "nodemon server.js --ignore './client/'"
> try this..

Worked for 5 minutes

**Comment by khiltonsolidcad** [comment]
I have been having the same problem and found this solution worked:
[https://github.com/saikat/react-apollo-starter-kit/issues/20#issuecomment-316651403](url)

**Comment by Vchau511** [comment]
> Using a parser like cookie parser or body parser can cause this is

How can you remove body parser and cookie parser?

**Comment by mythsand** [comment]
It's all about the port issue, check it! Changing the listening port, or restarting the process may be solved.

**Comment by this-mojtaba** [comment]
Hi my problem is the same,
and after that: 
 InternalOAuthError: Failed to fetch user profile
     at /home/mojtaba/Desktop/AdvancedNodeStarter/node_modules/passport-google-oauth20/lib/strategy.js:99:19
     at passBackControl (/home/mojtaba/Desktop/AdvancedNodeStarter/node_modules/oauth/lib/oauth2.js:132:9)
     at IncomingMessage.<anonymous> (/home/mojtaba/Desktop/AdvancedNodeStarter/node_modules/oauth/lib/oauth2.js:157:7)
     at IncomingMessage.emit (events.js:327:22)
     at endReadableNT (_stream_readable.js:1221:12)
     at processTicksAndRejections (internal/process/task_queues.js:84:21)

How to solve it?

**Comment by ChristopherHButler** [comment]
Hate to sound like a broken record but.... did anyone solve this one / find out WHY the error is occurring?

**Comment by alisequeira** [comment]
I think Stephen fix this error later on in the course. just keep watching the lectures.

**Comment by nblake707** [comment]
I was having this issue bc I was in a different area but forgot to add the new ip address under network access in mongoDb cluster. The error went away afterwards.

**Comment by Seelam-Ramesh-Reddy** [comment]
Same Issue with Angular. Please help ASAP

[HPM] POST /api/sn/queryParams -> http:127.0.0.1:8081
[HPM] Error occurred while trying to proxy request /api/sn/queryParams from localhost:4200 to http:127.0.0.1:8081 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

**Comment by MaltesBytes** [comment]
👀.   +1

**Comment by ydrea** [comment]
another one!
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

**Comment by next-ruan-rita** [comment]
Hi guys, I can using this method:

Replace localhost to 127.0.0.1 in your package.json proxy

**Comment by mdarif** [comment]
The issue is pretty much there in April 2022 as well.

**Comment by davrope** [comment]
In my case, this issue is related with something wrong in the backend server. I had a typo in a route (I typed a . instead of a ,). You can get a hint of what could go wrong if you read the error messages in the console and start debugging from there.

**Comment by SanduDS** [comment]
> Hi guys, I can using this method:
> 
> Replace localhost to 127.0.0.1 in your package.json proxy

Be sure to restart deployment server
