### ISSUE TITLE
Internal Server Issue(remote Heroku server for production) 

### ISSUE THREAD

**Issue by girlcodecrush** [StephenGrider/FullstackReactCode#42]
Hi Bobby, 

Moving here to github, regarding the issue above, let me share my project(see below). 

https://github.com/girlcodecrush/Fullstack_emaily

Thanks.

**Comment by dhuang612** [comment]
Hi are you still having this error?
What gets returned when you run 
heroku logs?

**Comment by shayannasir** [comment]
Similar Issue.
Getting **Internal server error** after selecting google account for OAuth.

`2020-01-29T11:14:18.439057+00:00 heroku[router]: at=info method=GET path="/auth/google/callback?code=4%2FvwGBTrWLfGr_aZ1GrZ9LrSBZplwMibBNwtfs-cm90zZQc-0AsX__6l4iFJcWx2BdxomIHTH2ZVJR3NWFqLa2QAI&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&authuser=0&prompt=none&session_state=fc72a5323a57669eb291c39f671ebdb3f93f20c7..832c" host=f-i-d-o.herokuapp.com request_id=cf1559f1-85f6-435a-b7c4-9e66f0d51787 fwd="122.163.154.248" dyno=web.1 connect=1ms service=142ms status=500 bytes=404 protocol=http
2020-01-29T11:14:18.436464+00:00 app[web.1]: Error
2020-01-29T11:14:18.436503+00:00 app[web.1]:     at /app/node_modules/passport-google-oauth20/lib/strategy.js:95:21
2020-01-29T11:14:18.436506+00:00 app[web.1]:     at passBackControl (/app/node_modules/oauth/lib/oauth2.js:132:9)
2020-01-29T11:14:18.436508+00:00 app[web.1]:     at IncomingMessage.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:157:7)
2020-01-29T11:14:18.436510+00:00 app[web.1]:     at emitNone (events.js:110:20)
2020-01-29T11:14:18.436511+00:00 app[web.1]:     at IncomingMessage.emit (events.js:207:7)
2020-01-29T11:14:18.436514+00:00 app[web.1]:     at endReadableNT (_stream_readable.js:1047:12)
2020-01-29T11:14:18.436515+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:102:11)
2020-01-29T11:14:18.436517+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:161:9)`

**Comment by dhuang612** [comment]
could you link your project?

**Comment by shayannasir** [comment]
Oh yes of course.
https://github.com/shayannasir/fido

Also, I just realised this maybe due to the depricated google+ auth(I tried fixing it, but alas)

Please excuse my ignorance though.
Thanks

**Comment by dhuang612** [comment]
what do the heroku logs say?
https://stackoverflow.com/questions/46021463/heroku-giving-500-error-with-little-information-internal-server-error
Have you done any googling into this?

**Comment by panna-ahmed** [comment]
@dhuang612  I am having the same error. Can you take a look? https://github.com/panna-ahmed/Surveyor

**Comment by Imshubh1234** [comment]
How to resolve **Internal server error** . In past I was successfully connected Heroku to Github but now I cant disconnect or connect it. I dont know why his problem appears while I did not changes any setting .

**Comment by robfuncken** [comment]
> How to resolve **Internal server error** . In past I was successfully connected Heroku to Github but now I cant disconnect or connect it. I dont know why his problem appears while I did not changes any setting .

I have the same issue reconnecting github to my Heroku account... I constantly get the internal server error with no more details..

**Comment by ebnanzhran** [comment]
Are the problem solved?\
