### ISSUE TITLE
Heroku Application error

### ISSUE THREAD

**Issue by ManLikeGhost** [StephenGrider/FullstackReactCode#48]
2019-01-15T15:22:25.802182+00:00 app[web.1]: npm ERR!                                                                                                                                                              2019-01-15T15:22:25.802484+00:00 app[web.1]: npm ERR! Failed at the server@1.0.0 start script.                                                                                                                     2019-01-15T15:22:25.803024+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                                                    2019-01-15T15:22:25.806344+00:00 app[web.1]:                                                                                                                                                                       2019-01-15T15:22:25.807126+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:                                                                                                                  2019-01-15T15:22:25.807593+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2019-01-15T15_22_25_785Z-debug.log                                                                                                       2019-01-15T15:22:25.923155+00:00 heroku[web.1]: State changed from starting to crashed                                                                                                                             2019-01-15T15:22:25.929275+00:00 heroku[web.1]: State changed from crashed to starting                                                                                                                             2019-01-15T15:22:25.900280+00:00 heroku[web.1]: Process exited with status 1                                                                                                                                       2019-01-15T15:22:42.093248+00:00 heroku[web.1]: Starting process with command `npm start`                                                                                                                          2019-01-15T15:22:46.266923+00:00 app[web.1]: module.js:487                                                                                                                                                         2019-01-15T15:22:46.266957+00:00 app[web.1]: throw err;                                                                                                                                                            2019-01-15T15:22:46.266959+00:00 app[web.1]: ^                                                                                                                                                                     2019-01-15T15:22:46.266961+00:00 app[web.1]:                                                                                                                                                                       2019-01-15T15:22:46.266963+00:00 app[web.1]: Error: Cannot find module 'passport'                                                                                                                                  2019-01-15T15:22:46.266965+00:00 app[web.1]: at Function.Module._resolveFilename (module.js:485:15)                                                                                                                2019-01-15T15:22:46.266967+00:00 app[web.1]: at Function.Module._load (module.js:437:25)                                                                                                                           2019-01-15T15:22:46.266968+00:00 app[web.1]: at Module.require (module.js:513:17)                                                                                                                                  2019-01-15T15:22:46.266970+00:00 app[web.1]: at require (internal/module.js:11:18)                                                                                                                                 2019-01-15T15:22:46.266972+00:00 app[web.1]: at Object. (/app/index.js:4:18)                                                                                                                            2019-01-15T15:22:46.266973+00:00 app[web.1]: at Module._compile (module.js:569:30)                                                                                                                                 2019-01-15T15:22:46.266975+00:00 app[web.1]: at Object.Module._extensions..js (module.js:580:10)                                                                                                                   2019-01-15T15:22:46.266976+00:00 app[web.1]: at Module.load (module.js:503:32)                                                                                                                                     2019-01-15T15:22:46.266978+00:00 app[web.1]: at tryModuleLoad (module.js:466:12)                                                                                                                                   2019-01-15T15:22:46.266979+00:00 app[web.1]: at Function.Module._load (module.js:458:3)                                                                                                                            2019-01-15T15:22:46.266981+00:00 app[web.1]: at Function.Module.runMain (module.js:605:10)                                                                                                                         2019-01-15T15:22:46.266982+00:00 app[web.1]: at startup (bootstrap_node.js:158:16)                                                                                                                                 2019-01-15T15:22:46.266984+00:00 app[web.1]: at bootstrap_node.js:575:3                                                                                                                                            2019-01-15T15:22:46.303537+00:00 app[web.1]: npm ERR! code ELIFECYCLE                                                                                                                                              2019-01-15T15:22:46.304326+00:00 app[web.1]: npm ERR! errno 1                                                                                                                                                      2019-01-15T15:22:46.305039+00:00 app[web.1]: npm ERR! server@1.0.0 start: `node index.js`                                                                                                                          2019-01-15T15:22:46.305434+00:00 app[web.1]: npm ERR! Exit status 1                                                                                                                                                2019-01-15T15:22:46.305908+00:00 app[web.1]: npm ERR!                                                                                                                                                              2019-01-15T15:22:46.306343+00:00 app[web.1]: npm ERR! Failed at the server@1.0.0 start script.                                                                                                                     2019-01-15T15:22:46.306916+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                                                    2019-01-15T15:22:46.310663+00:00 app[web.1]:                                                                                                                                                                       2019-01-15T15:22:46.311505+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:                                                                                                                  2019-01-15T15:22:46.311679+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2019-01-15T15_22_46_289Z-debug.log                                                                                                       2019-01-15T15:22:46.413514+00:00 heroku[web.1]: Process exited with status 1                                                                                                                                       2019-01-15T15:22:56.003574+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=tranquil-fjord-71188.herokuapp.com request_id=fc83f5dc-d4c1-4f32-853f-395dee5ea663 fwd="41.217.117. 212" dyno= connect= service= status=503 bytes= protocol=https                                                                                                                                                      2019-01-15T15:24:36.386551+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=tranquil-fjord-71188.herokuapp.com request_id=a356786a-9533-4b4d-8a38-9d85c1db99a7 fwd="41.217.117. 212" dyno= connect= service= status=503 bytes= protocol=https                                                                                                                                                      2019-01-15T15:24:37.232472+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=tranquil-fjord-71188.herokuapp.com request_id=03f848f9-6cda-4456-910f-41921e36b41b fwd=" 41.217.117.212" dyno= connect= service= status=503 bytes= protocol=https                                                                                                                                           2019-01-15T15:44:07.594452+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=tranquil-fjord-71188.herokuapp.com request_id=db49ca9b-c24c-47b9-bda3-58efb9807933 fwd="41.217.117. 212" dyno= connect= service= status=503 bytes= protocol=https                                                                                                                                                      2019-01-15T15:44:08.427847+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=tranquil-fjord-71188.herokuapp.com request_id=1efeeb4c-429e-436b-b010-aba258ba314b fwd=" 41.217.117.212" dyno= connect= service= status=503 bytes= protocol=https
--
===================================================================

2019-01-15T15:46:25.526334+00:00 app[web.1]: npm ERR! Failed at the server@1.0.0 start script.
2019-01-15T15:46:25.526425+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-01-15T15:46:25.527386+00:00 app[web.1]: 
2019-01-15T15:46:25.527512+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2019-01-15T15:46:25.527568+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2019-01-15T15_46_25_520Z-debug.log
2019-01-15T15:46:25.603526+00:00 heroku[web.1]: State changed from starting to crashed
2019-01-15T15:46:25.576924+00:00 heroku[web.1]: Process exited with status 1
2019-01-15T16:10:08.204841+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=tranquil-fjord-71188.herokuapp.com request_id=75f88daa-4791-462b-9f0e-4c029e203ff4 fwd="197.255.170.189" dyno= connect= service= status=503 bytes= protocol=https
2019-01-15T16:10:08.946361+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=tranquil-fjord-71188.herokuapp.com request_id=c095d312-bf4f-46e3-b7c1-4905269ba67f fwd="197.255.170.189" dyno= connect= service= status=503 bytes= protocol=https
2019-01-15T16:19:20.341707+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=tranquil-fjord-71188.herokuapp.com request_id=901d485f-d451-4790-98de-7c9545e721b3 fwd="197.255.170.189" dyno= connect= service= status=503 bytes= protocol=https

**Comment by eponymz** [comment]
```2019-01-15T16:19:20.341707+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=tranquil-fjord-71188.herokuapp.com request_id=901d485f-d451-4790-98de-7c9545e721b3 fwd="197.255.170.189" dyno= connect= service= status=503 bytes= protocol=https```

Looks like your base URL is returning 503.
https://httpstatuses.com/503

In one of the logs it states "cannot find module 'passport'" somewhere you have a borked import. Do you have this stored in a GitHub repo by chance?
